import React, { useState, useEffect } from 'react';
import { Shield, FileText, Landmark } from 'lucide-react';

const InfoPolicies = ({ defaultTab = 'privacy' }) => {
  const [activeTab, setActiveTab] = useState(defaultTab);

  useEffect(() => {
    setActiveTab(defaultTab);
  }, [defaultTab]);

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      {/* Title */}
      <div className="border-b border-slate-200 dark:border-slate-800 pb-6 text-center">
        <h1 className="text-2xl md:text-3xl font-extrabold text-slate-800 dark:text-white">Legal Agreements & Policies</h1>
        <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1">SmartPredict AI Regulatory & System Compliance Center</p>
      </div>

      {/* Tabs */}
      <div className="flex justify-center gap-6 border-b border-slate-100 dark:border-slate-800 pb-3 font-bold text-xs uppercase text-slate-400">
        <button 
          onClick={() => setActiveTab('privacy')}
          className={`pb-3 border-b-2 transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'privacy' ? 'border-primary-600 text-primary-600' : 'border-transparent hover:text-slate-600'}`}
        >
          <Shield className="w-4 h-4" /> Privacy Framework
        </button>
        <button 
          onClick={() => setActiveTab('terms')}
          className={`pb-3 border-b-2 transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'terms' ? 'border-primary-600 text-primary-600' : 'border-transparent hover:text-slate-600'}`}
        >
          <FileText className="w-4 h-4" /> Terms of Service
        </button>
        <button 
          onClick={() => setActiveTab('license')}
          className={`pb-3 border-b-2 transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'license' ? 'border-primary-600 text-primary-600' : 'border-transparent hover:text-slate-600'}`}
        >
          <Landmark className="w-4 h-4" /> Data Sources License
        </button>
      </div>

      {/* Content */}
      <div className="glass-card p-8 border border-slate-200 dark:border-slate-800 shadow-xl space-y-6 text-slate-600 dark:text-slate-400 font-light text-xs leading-relaxed">
        {activeTab === 'privacy' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-800 dark:text-white">Privacy Framework</h2>
            <p><strong>Last Updated: July 2026</strong></p>
            <p>SmartPredict AI is committed to securing user account details and transaction parameters. This Privacy Policy details how we handle database queries, user profile information, and local cookies.</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">1. Data Storage & Volatility</h3>
            <p>All property parameters logged during price predictions are stored in a local encrypted database. We only record input variables (carpet area, BHK configurations, and location coordinates) to generate user-specific historical reports.</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">2. Cookies & Sessions</h3>
            <p>If you select the "Remember Me" option during login, the system stores your user authentication metadata inside the browser's `localStorage` so that your session persists. If unchecked, the session is kept temporarily in memory (`sessionStorage`) and deleted when you close the tab.</p>
          </div>
        )}

        {activeTab === 'terms' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-800 dark:text-white">Terms of Service</h2>
            <p><strong>Last Updated: July 2026</strong></p>
            <p>By accessing the SmartPredict AI Price Prediction system, you agree to the following terms, conditions, and disclaimers.</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">1. Algorithmic Predictions</h3>
            <p>This application generates real estate valuations using supervised machine learning algorithms (Random Forest and XGBoost regressions). These values represent estimated market coefficients based on historical transaction datasets and do not guarantee actual transaction quotes.</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">2. Non-Commercial Advice</h3>
            <p>The pricing results, appreciation metrics, and location ratings generated by the system are for educational and major project validation analysis only. Users should perform physical title validations and consult certified agents before buying real estate properties.</p>
          </div>
        )}

        {activeTab === 'license' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-800 dark:text-white">Data Sources License</h2>
            <p><strong>Last Updated: July 2026</strong></p>
            <p>SmartPredict AI operates on a compilation of municipal real estate registries, public infrastructure databases, and synthetic demographic corridors.</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">1. Open Data Attribution</h3>
            <p>Our location transit calculations use open public mapping parameters representing walking distance boundaries to metro stations, transit routes, and commercial retail nodes in Indian metropolitan areas (Mumbai, Delhi, Bangalore, Hyderabad, Pune).</p>
            <h3 className="font-bold text-slate-800 dark:text-white mt-4 text-xs">2. Synthetic Corridors</h3>
            <p>To comply with data privacy boundaries, the base training dataset consists of 5,000+ synthetic files modeled to match authentic transaction variables across target metropolitan micro-markets.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default InfoPolicies;
